---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: dev
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/yakupars/podinfo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: podinfo
  namespace: dev
spec:
  interval: 1m0s
  chart: ./charts/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client

