---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev
spec:
  chart:
    spec:
      chart: charts
      sourceRef:
        kind: GitRepository
        name: flux-dev
  install: {}
  interval: 30s

